version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-team-reboott
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: team_reboott_db
    ports:
      - "3307:3306"
    volumes:
      - team_reboott_mysql_data:/var/lib/mysql

  redis:
    image: redis:7.2.4
    container_name: redis-team-reboott
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - team_reboott_redis_data:/data

volumes:
  team_reboott_mysql_data:
  team_reboott_redis_data: